pipeline {
    agent { label 'agent-master' }

    options {
        skipDefaultCheckout(true)
    }

    environment {
        SERVICE_NAME    = 'frontend'

        GIT_REPO        = 'http://github.com/Sayub-cs/app-DevSecOps'
        GIT_BRANCH      = 'master'

        DockerHub_REGISTRY = 'sayubb'
        DockerHub_repo  = 'app-angular-springing-frontend'
        IMAGE_NAME      = "${DockerHub_REGISTRY}/${DockerHub_repo}"
        IMAGE_TAG       = "${BUILD_NUMBER}"

        //GITLAB_HOST     = 'gitlab.local'
        //K8S_BRANCH      = 'master'
        DEPLOYMENT_FILE = 'frontend/deployment.yaml'
    }

    stages {

        stage('Checkout Frontend Repo') {
            steps {
                git branch: "${GIT_BRANCH}",
                    credentialsId: 'github-creds',
                    url: "${GIT_REPO}"
            }
        }

        stage('Verify Frontend Project') {
            steps {
                sh """
                    echo "==> Current workspace"
                    pwd
                    ls -la

                    echo "==> Verify frontend files"
                    test -f Dockerfile
                    test -f package.json
                    test -f angular.json
                    test -d src
                """
            }
        }

        stage('Verify Docker Access') {
            steps {
                sh '''
                    docker --version
                    docker ps
                '''
            }
        }

        stage('Clean Docker') {
            steps {
                sh 'docker system prune -a -f || true'
                sh 'docker builder prune -a -f || true'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
                '''
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKERHUB_USER',
                    passwordVariable: 'DOCKERHUB_PASS'
                )]) {
                    sh '''
                        echo "${DOCKERHUB_PASS}" | docker login ${DockerHub_REGISTRY} -u "${DOCKERHUB_USER}" --password-stdin
                    '''
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                sh '''
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    docker push ${IMAGE_NAME}:latest
                '''
            }
        }

       
    }

    post {
        always {
            sh '''
                docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true
                docker rmi ${IMAGE_NAME}:latest || true
                docker logout ${DockerHub_REGISTRY} || true
            '''
        }

        success {
            echo "frontend image pushed successfully: ${IMAGE_NAME}:${IMAGE_TAG}"
        }

        failure {
            echo "frontend pipeline failed. Check Jenkins logs."
        }
    }
}