pipeline {
    agent { label 'agent-master' }

    options {
        skipDefaultCheckout(true)
    }

    environment {
        SERVICE_NAME    = 'business-service'
        SERVICE_DIR     = 'backend/business-service'

      
        GIT_REPO        = 'https://github.com/Sayub-cs/app-DevSecOps.git'
        GIT_BRANCH      = 'main'

        DockerHub_REGISTRY = 'docker.io'
        DockerHub_user  = 'sayubb'
        DockerHub_repo  = 'app-angular-springing-business-service'
        IMAGE_NAME      = "${DockerHub_REGISTRY}/${DockerHub_user}/${DockerHub_repo}"
        IMAGE_TAG       = "${BUILD_NUMBER}"

        //GITLAB_HOST     = 'http://gitlab.local/pfe/k8s-manifests.git'
        //K8S_BRANCH      = 'master'
        DEPLOYMENT_FILE = 'k8s/business-service/deployment.yaml'
    }

    stages {
        stage('Checkout Backend Repo') {
            steps {
                git branch: "${GIT_BRANCH}",
                    credentialsId: 'github-creds',
                    url: "${GIT_REPO}"
            }
        }

        stage('Verify Project') {
            steps {
                sh """
                    pwd
                    ls -la
                    test -d ${SERVICE_DIR}
                    test -f ${SERVICE_DIR}/Dockerfile
                    test -f ${SERVICE_DIR}/pom.xml
                    test -d ${SERVICE_DIR}/src
                    ls -la ${SERVICE_DIR}
                """
            }
        }

        stage('Verify Docker Access') {
            steps {
                sh '''
                    docker --version
                    docker ps
                '''
            }
        }

        stage('Clean Docker') {
            steps {
                sh 'docker system prune -a -f || true'
                sh 'docker builder prune -a -f || true'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ${SERVICE_DIR}
                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
                """
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKERHUB_USER',
                    passwordVariable: 'DOCKERHUB_PASS'
                )]) {
                    sh '''
                        echo "${DOCKERHUB_PASS}" | docker login -u "${DockerHub_user}" --password-stdin
                    '''
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                sh """
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    docker push ${IMAGE_NAME}:latest
                """
            }
        }

       
    }

    post {
        always {
            sh """
                docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true
                docker rmi ${IMAGE_NAME}:latest || true
                docker logout ${DockerHub_REGISTRY} || true
            """
        }

        success {
            echo "${SERVICE_NAME} image pushed successfully: ${IMAGE_NAME}:${IMAGE_TAG}"
        }

        failure {
            echo "${SERVICE_NAME} pipeline failed. Check Jenkins logs."
        }
    }
}