apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-secrets.yaml
  - 02-postgres.yaml

  - discovery-service/deployment.yaml
  - discovery-service/service.yaml

  - auth-service/deployment.yaml
  - auth-service/service.yaml

  - user-service/deployment.yaml
  - user-service/service.yaml

  - business-service/deployment.yaml
  - business-service/service.yaml

  - api-gateway/deployment.yaml
  - api-gateway/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - ingress/ingress.yaml