pipeline {
    agent { label 'agent-master' }

    options {
        skipDefaultCheckout(true)
    }

    environment {
        SERVICE_NAME    = 'api-gateway'
        SERVICE_DIR     = 'backend/api-gateway'

        GIT_REPO        = 'https://github.com/Sayub-cs/app-DevSecOps.git'
        GIT_BRANCH      = 'main'

        DockerHub_REGISTRY = 'sayubb'
        DockerHub_repo  = 'app-angular-springing-api-gateway'
        IMAGE_NAME      = "${DockerHub_REGISTRY}/${DockerHub_repo}"
        IMAGE_TAG       = "${BUILD_NUMBER}"

        //K8S_REPO        = ''
        //K8S_BRANCH      ='master'
        DEPLOYMENT_FILE = 'k8s/api-gateway/deployment.yaml'
    }

    stages {

        stage('Checkout Backend Repo') {
            steps {
                git branch: "${GIT_BRANCH}",
                    credentialsId: 'github-creds',
                    url: "${GIT_REPO}"
            }
        }

        stage('Verify Api Gateway Project') {
            steps {
                sh """
                    echo "==> Current workspace"
                    pwd

                    echo "==> Backend repo structure"
                    ls -la

                    echo "==> Verify api-gateway files"
                    test -d ${SERVICE_DIR}
                    test -f ${SERVICE_DIR}/Dockerfile
                    test -f ${SERVICE_DIR}/pom.xml
                    test -d ${SERVICE_DIR}/src

                    echo "==> Api Gateway structure"
                    ls -la ${SERVICE_DIR}
                """
            }
        }

        stage('Verify Docker Access') {
            steps {
                sh '''
                    docker --version
                    docker ps
                '''
            }
        }

        stage('Clean Docker') {
            steps {
                sh 'docker system prune -a -f || true'
                sh 'docker builder prune -a -f || true'
            }
        }

       stage('Build Docker Image') {
    environment {
        DOCKER_BUILDKIT = '0'
    }
    steps {
        sh '''
            echo "DOCKER_BUILDKIT=$DOCKER_BUILDKIT"

            docker build \
              --progress=plain \
              -t ${IMAGE_NAME}:${IMAGE_TAG} \
              ${SERVICE_DIR}

            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
        '''
    }
 }

        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKERHUB_USER',
                    passwordVariable: 'DOCKERHUB_PASS'
                )]) {
                    sh '''
                        echo "${DOCKERHUB_PASS}" | docker login ${DOCKERHUB_REGISTRY} -u "${DOCKERHUB_USER}" --password-stdin
                    '''
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                sh """
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    docker push ${IMAGE_NAME}:latest
                """
            }
        }

    }

    post {
        always {
            sh """
                docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true
                docker rmi ${IMAGE_NAME}:latest || true
                docker logout ${DockerHub_REGISTRY} || true
            """
        }

        success {
            echo "Api Gateway image pushed successfully: ${IMAGE_NAME}:${IMAGE_TAG}"
        }

        failure {
            echo "Api Gateway pipeline failed. Check Jenkins logs."
        }
    }
}